language: ruby

rvm:
  - jruby-head
  - jruby-18mode
  - jruby-19mode

env:
  - NUODB_HOME=/opt/nuodb CLASSPATH=/opt/nuodb/jar/nuodbjdbc.jar NUODB_VERSION=1.2
  - NUODB_HOME=/opt/nuodb CLASSPATH=/opt/nuodb/jar/nuodbjdbc.jar NUODB_VERSION=1.1.1
  - NUODB_HOME=/opt/nuodb CLASSPATH=/opt/nuodb/jar/nuodbjdbc.jar NUODB_VERSION=1.1
  - NUODB_HOME=/opt/nuodb CLASSPATH=/opt/nuodb/jar/nuodbjdbc.jar NUODB_VERSION=1.0.2
  - NUODB_HOME=/opt/nuodb CLASSPATH=/opt/nuodb/jar/nuodbjdbc.jar NUODB_VERSION=1.0.1

notifications:
  recipients:
    - buck.robert.j@gmail.com
    - rbuck@nuodb.com
    - jgetto@nuodb.com

before_install:
  - wget http://www.nuodb.com/latest/releases/nuodb-${NUODB_VERSION}.linux.x64.deb --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - sleep 2

before_script:
  - java -jar ${NUODB_HOME}/jar/nuodbmanager.jar --broker localhost --user domain --password bird --command "start process sm database test host localhost archive /var/tmp/nuodb initialize true waitForRunning true"
  - java -jar ${NUODB_HOME}/jar/nuodbmanager.jar --broker localhost --user domain --password bird --command "start process te database test host localhost options '--dba-user dba --dba-password baz' waitForRunning true"
  - echo "create user cloud password 'user';" | ${NUODB_HOME}/bin/nuosql test@localhost --user dba --password baz

script:
  - jruby -S gem update --system
  - jruby -S bundle install
  - NUODB_ROOT=NUODB_HOME jruby -S rake clean build spec install

after_script:
  - sudo dpkg -r nuodb
