language: ruby

rvm:
  - jruby-head
  - jruby-19mode

env:
  - NUODB_HOME=/opt/nuodb NUODB_VERSION=2.0.3
  - NUODB_HOME=/opt/nuodb NUODB_VERSION=2.0.4

notifications:
  recipients:
    - buck.robert.j@gmail.com
    - rbuck@nuodb.com
    - jgetto@nuodb.com
    - tgates@nuodb.com

before_install:
  - wget http://download.nuohub.org/nuodb-${NUODB_VERSION}.linux.x64.deb --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - sleep 2

before_script:
  - java -jar ${NUODB_HOME}/jar/nuodbmanager.jar --broker localhost --user domain --password bird --command "start process sm database test host localhost archive /var/tmp/nuodb initialize true waitForRunning true"
  - java -jar ${NUODB_HOME}/jar/nuodbmanager.jar --broker localhost --user domain --password bird --command "start process te database test host localhost options '--dba-user dba --dba-password dba' waitForRunning true"
  - echo "create user cloud password 'user';" | ${NUODB_HOME}/bin/nuosql test@localhost --user dba --password dba

script:
  - jruby -S bundle install
  - NUODB_ROOT=${NUODB_HOME} jruby -S rake clean build spec install

after_script:
  - sudo dpkg -r nuodb
