language: ruby

rvm:
  - jruby-head
  - jruby-18mode
  - jruby-19mode

env:
  - NUODB_ROOT=/opt/nuodb

notifications:
  recipients:
    - buck.robert.j@gmail.com
    - rbuck@nuodb.com

before_script:
  - wget http://www.nuodb.com/latest/nuodb-1.0-GA.linux.x86_64.deb --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb

script:
  - jruby -S bundle install
  - jruby -S gem list
  - NUODB_ROOT=/opt/nuodb jruby -S bundle exec rake build install
  - jruby -S gem list

after_script:
  - sudo dpkg -r nuodb
